services:
  php-apache:
    image: php:8.2-apache
    container_name: grad-spbss-php-apache-1
    volumes:
      - .:/var/www/html  # ตรวจสอบว่ามีบรรทัดนี้ และจุดข้างหน้าต้องมีอยู่
    ports:
      - "8082:80"